{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "56be193d",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-10-01 13:20:33.752890: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2022-10-01 13:20:33.948382: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
      "2022-10-01 13:20:34.614449: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory\n",
      "2022-10-01 13:20:34.614570: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory\n",
      "2022-10-01 13:20:34.614578: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "from tensorflow.keras.models import Sequential\n",
    "from tensorflow.keras.layers import Dense\n",
    "from scikeras.wrappers import KerasRegressor\n",
    "from sklearn.model_selection import cross_val_score\n",
    "from sklearn.model_selection import KFold\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.pipeline import Pipeline\n",
    "\n",
    "from sklearn.compose import ColumnTransformer"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "ca97ab37",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>index</th>\n",
       "      <th>address</th>\n",
       "      <th>cost_text</th>\n",
       "      <th>Bed</th>\n",
       "      <th>Bath</th>\n",
       "      <th>Park</th>\n",
       "      <th>property_type</th>\n",
       "      <th>desc_head</th>\n",
       "      <th>LocID</th>\n",
       "      <th>longitude</th>\n",
       "      <th>latitude</th>\n",
       "      <th>Median_tot_prsnl_inc_weekly</th>\n",
       "      <th>Median_rent_weekly</th>\n",
       "      <th>Median_tot_fam_inc_weekly</th>\n",
       "      <th>Median_tot_hhd_inc_weekly</th>\n",
       "      <th>total_population</th>\n",
       "      <th>SA2_NAME21</th>\n",
       "      <th>duration_mins</th>\n",
       "      <th>Offence Count</th>\n",
       "      <th>SA2_CODE_2021</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>https://www.domain.com.au/warrandyte-vic-3113-...</td>\n",
       "      <td>Warrandyte VIC 3113</td>\n",
       "      <td>875.0</td>\n",
       "      <td>5</td>\n",
       "      <td>3</td>\n",
       "      <td>3</td>\n",
       "      <td>House</td>\n",
       "      <td>mud brick magic</td>\n",
       "      <td>211021262</td>\n",
       "      <td>145.209992</td>\n",
       "      <td>-37.747366</td>\n",
       "      <td>930.0</td>\n",
       "      <td>481.0</td>\n",
       "      <td>3051.0</td>\n",
       "      <td>2779.0</td>\n",
       "      <td>8781.0</td>\n",
       "      <td>Warrandyte - Wonga Park</td>\n",
       "      <td>&gt;50.0</td>\n",
       "      <td>859.0</td>\n",
       "      <td>211021262.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                               index              address  \\\n",
       "0  https://www.domain.com.au/warrandyte-vic-3113-...  Warrandyte VIC 3113   \n",
       "\n",
       "   cost_text  Bed  Bath  Park property_type        desc_head      LocID  \\\n",
       "0      875.0    5     3     3         House  mud brick magic  211021262   \n",
       "\n",
       "    longitude   latitude  Median_tot_prsnl_inc_weekly  Median_rent_weekly  \\\n",
       "0  145.209992 -37.747366                        930.0               481.0   \n",
       "\n",
       "   Median_tot_fam_inc_weekly  Median_tot_hhd_inc_weekly  total_population  \\\n",
       "0                     3051.0                     2779.0            8781.0   \n",
       "\n",
       "                SA2_NAME21 duration_mins  Offence Count  SA2_CODE_2021  \n",
       "0  Warrandyte - Wonga Park         >50.0          859.0    211021262.0  "
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# load dataset\n",
    "property_df = pd.read_csv(\"../data/curated/full_data.csv\")\n",
    "X = property_df\n",
    "X2 = X[['SA2_NAME21']].groupby(by=\"SA2_NAME21\")[\"SA2_NAME21\"].count()\n",
    "X2 = pd.DataFrame(X2)\n",
    "X2.columns=[\"count\"]\n",
    "single_counts = X2[X2['count']==1].reset_index()['SA2_NAME21'].tolist() # can improve this later with bootstrapping\n",
    "X = X[~X[\"SA2_NAME21\"].isin(single_counts)]\n",
    "X.head(1)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "909e478e",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_58905/1187906559.py:9: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  vic_sf.dropna(inplace=True)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>SA2_CODE21</th>\n",
       "      <th>SA2_NAME21</th>\n",
       "      <th>CHG_FLAG21</th>\n",
       "      <th>CHG_LBL21</th>\n",
       "      <th>SA3_CODE21</th>\n",
       "      <th>SA3_NAME21</th>\n",
       "      <th>SA4_CODE21</th>\n",
       "      <th>SA4_NAME21</th>\n",
       "      <th>GCC_CODE21</th>\n",
       "      <th>GCC_NAME21</th>\n",
       "      <th>STE_CODE21</th>\n",
       "      <th>STE_NAME21</th>\n",
       "      <th>AUS_CODE21</th>\n",
       "      <th>AUS_NAME21</th>\n",
       "      <th>AREASQKM21</th>\n",
       "      <th>LOCI_URI21</th>\n",
       "      <th>geometry</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1104</th>\n",
       "      <td>214011375</td>\n",
       "      <td>Seaford (Vic.)</td>\n",
       "      <td>0</td>\n",
       "      <td>No change</td>\n",
       "      <td>21401</td>\n",
       "      <td>Frankston</td>\n",
       "      <td>214</td>\n",
       "      <td>Mornington Peninsula</td>\n",
       "      <td>2GMEL</td>\n",
       "      <td>Greater Melbourne</td>\n",
       "      <td>2</td>\n",
       "      <td>Victoria</td>\n",
       "      <td>AUS</td>\n",
       "      <td>Australia</td>\n",
       "      <td>12.4321</td>\n",
       "      <td>http://linked.data.gov.au/dataset/asgsed3/SA2/...</td>\n",
       "      <td>POLYGON ((145.12445 -38.10103, 145.12447 -38.1...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "     SA2_CODE21      SA2_NAME21 CHG_FLAG21  CHG_LBL21 SA3_CODE21 SA3_NAME21  \\\n",
       "1104  214011375  Seaford (Vic.)          0  No change      21401  Frankston   \n",
       "\n",
       "     SA4_CODE21            SA4_NAME21 GCC_CODE21         GCC_NAME21  \\\n",
       "1104        214  Mornington Peninsula      2GMEL  Greater Melbourne   \n",
       "\n",
       "     STE_CODE21 STE_NAME21 AUS_CODE21 AUS_NAME21  AREASQKM21  \\\n",
       "1104          2   Victoria        AUS  Australia     12.4321   \n",
       "\n",
       "                                             LOCI_URI21  \\\n",
       "1104  http://linked.data.gov.au/dataset/asgsed3/SA2/...   \n",
       "\n",
       "                                               geometry  \n",
       "1104  POLYGON ((145.12445 -38.10103, 145.12447 -38.1...  "
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import geopandas as gpd\n",
    "# sf stands for shape file\n",
    "australia_sf = gpd.read_file(\"../data/raw/shapefiles/Statistical_area_level2/SA2_2021_AUST_GDA2020.shp\")\n",
    "australia_sf.head(3)\n",
    "# seperate suburbs that are in Victoria\n",
    "vic_sf = australia_sf[australia_sf['STE_NAME21'] == 'Victoria']\n",
    "\n",
    "# drop the null location ID values\n",
    "vic_sf.dropna(inplace=True)\n",
    "vic_sf.head(1)\n",
    "vic_sf.where(vic_sf[\"SA2_NAME21\"] == \"Seaford (Vic.)\").dropna()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "cf133682",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/sesshah/anaconda3/lib/python3.9/site-packages/geopandas/geodataframe.py:1472: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  super().__setitem__(key, value)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "780    POINT (144.96089 -37.80918)\n",
       "Name: geometry, dtype: geometry"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "vic_centroid_sf = vic_sf\n",
    "vic_centroid_sf['geometry'] = vic_sf['geometry'].to_crs('+proj=cea').centroid.to_crs(vic_sf['geometry'].crs)\n",
    "cbd_loc = vic_centroid_sf.where(vic_centroid_sf['SA2_NAME21'] == 'Melbourne CBD - North').dropna()['geometry']\n",
    "cbd_loc"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "615173a0",
   "metadata": {},
   "outputs": [],
   "source": [
    "# function taken from https://stackoverflow.com/a/56661833\n",
    "\n",
    "from math import radians, cos, sin, asin, sqrt, inf\n",
    "\n",
    "def haversine(lon1, lat1, lon2, lat2):\n",
    "    \"\"\"\n",
    "    Calculate the great circle distance between two points \n",
    "    on the earth (specified in decimal degrees)\n",
    "    \"\"\"\n",
    "    # convert decimal degrees to radians \n",
    "    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])\n",
    "\n",
    "    # haversine formula \n",
    "    dlon = lon2 - lon1 \n",
    "    dlat = lat2 - lat1 \n",
    "    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2\n",
    "    c = 2 * asin(sqrt(a)) \n",
    "    r = 6371 # Radius of earth in kilometers. Use 3956 for miles\n",
    "    return c * r\n",
    "\n",
    "# this function converts two floats to a point that is recognised by Shapely\n",
    "def point_to_dist(row):\n",
    "    dist = haversine(row[\"geometry\"].y, row[\"geometry\"].x, cbd_loc.y, cbd_loc.x)\n",
    "    return dist\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "347c3d34",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>SA2_CODE21</th>\n",
       "      <th>SA2_NAME21</th>\n",
       "      <th>CHG_FLAG21</th>\n",
       "      <th>CHG_LBL21</th>\n",
       "      <th>SA3_CODE21</th>\n",
       "      <th>SA3_NAME21</th>\n",
       "      <th>SA4_CODE21</th>\n",
       "      <th>SA4_NAME21</th>\n",
       "      <th>GCC_CODE21</th>\n",
       "      <th>GCC_NAME21</th>\n",
       "      <th>STE_CODE21</th>\n",
       "      <th>STE_NAME21</th>\n",
       "      <th>AUS_CODE21</th>\n",
       "      <th>AUS_NAME21</th>\n",
       "      <th>AREASQKM21</th>\n",
       "      <th>LOCI_URI21</th>\n",
       "      <th>geometry</th>\n",
       "      <th>count</th>\n",
       "      <th>cbd_dist</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>780</th>\n",
       "      <td>206041504</td>\n",
       "      <td>Melbourne CBD - North</td>\n",
       "      <td>1</td>\n",
       "      <td>New</td>\n",
       "      <td>20604</td>\n",
       "      <td>Melbourne City</td>\n",
       "      <td>206</td>\n",
       "      <td>Melbourne - Inner</td>\n",
       "      <td>2GMEL</td>\n",
       "      <td>Greater Melbourne</td>\n",
       "      <td>2</td>\n",
       "      <td>Victoria</td>\n",
       "      <td>AUS</td>\n",
       "      <td>Australia</td>\n",
       "      <td>0.5616</td>\n",
       "      <td>http://linked.data.gov.au/dataset/asgsed3/SA2/...</td>\n",
       "      <td>POINT (144.96089 -37.80918)</td>\n",
       "      <td>252</td>\n",
       "      <td>0.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>781</th>\n",
       "      <td>206041505</td>\n",
       "      <td>Melbourne CBD - West</td>\n",
       "      <td>1</td>\n",
       "      <td>New</td>\n",
       "      <td>20604</td>\n",
       "      <td>Melbourne City</td>\n",
       "      <td>206</td>\n",
       "      <td>Melbourne - Inner</td>\n",
       "      <td>2GMEL</td>\n",
       "      <td>Greater Melbourne</td>\n",
       "      <td>2</td>\n",
       "      <td>Victoria</td>\n",
       "      <td>AUS</td>\n",
       "      <td>Australia</td>\n",
       "      <td>1.0051</td>\n",
       "      <td>http://linked.data.gov.au/dataset/asgsed3/SA2/...</td>\n",
       "      <td>POINT (144.95871 -37.81672)</td>\n",
       "      <td>200</td>\n",
       "      <td>0.728392</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>779</th>\n",
       "      <td>206041503</td>\n",
       "      <td>Melbourne CBD - East</td>\n",
       "      <td>1</td>\n",
       "      <td>New</td>\n",
       "      <td>20604</td>\n",
       "      <td>Melbourne City</td>\n",
       "      <td>206</td>\n",
       "      <td>Melbourne - Inner</td>\n",
       "      <td>2GMEL</td>\n",
       "      <td>Greater Melbourne</td>\n",
       "      <td>2</td>\n",
       "      <td>Victoria</td>\n",
       "      <td>AUS</td>\n",
       "      <td>Australia</td>\n",
       "      <td>0.8020</td>\n",
       "      <td>http://linked.data.gov.au/dataset/asgsed3/SA2/...</td>\n",
       "      <td>POINT (144.96860 -37.81277)</td>\n",
       "      <td>138</td>\n",
       "      <td>0.917602</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>771</th>\n",
       "      <td>206041117</td>\n",
       "      <td>Carlton</td>\n",
       "      <td>0</td>\n",
       "      <td>No change</td>\n",
       "      <td>20604</td>\n",
       "      <td>Melbourne City</td>\n",
       "      <td>206</td>\n",
       "      <td>Melbourne - Inner</td>\n",
       "      <td>2GMEL</td>\n",
       "      <td>Greater Melbourne</td>\n",
       "      <td>2</td>\n",
       "      <td>Victoria</td>\n",
       "      <td>AUS</td>\n",
       "      <td>Australia</td>\n",
       "      <td>1.8187</td>\n",
       "      <td>http://linked.data.gov.au/dataset/asgsed3/SA2/...</td>\n",
       "      <td>POINT (144.96781 -37.80049)</td>\n",
       "      <td>218</td>\n",
       "      <td>1.103787</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>786</th>\n",
       "      <td>206041510</td>\n",
       "      <td>West Melbourne - Residential</td>\n",
       "      <td>1</td>\n",
       "      <td>New</td>\n",
       "      <td>20604</td>\n",
       "      <td>Melbourne City</td>\n",
       "      <td>206</td>\n",
       "      <td>Melbourne - Inner</td>\n",
       "      <td>2GMEL</td>\n",
       "      <td>Greater Melbourne</td>\n",
       "      <td>2</td>\n",
       "      <td>Victoria</td>\n",
       "      <td>AUS</td>\n",
       "      <td>Australia</td>\n",
       "      <td>0.8247</td>\n",
       "      <td>http://linked.data.gov.au/dataset/asgsed3/SA2/...</td>\n",
       "      <td>POINT (144.94977 -37.80857)</td>\n",
       "      <td>67</td>\n",
       "      <td>1.237667</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1009</th>\n",
       "      <td>212031557</td>\n",
       "      <td>Cranbourne East - North</td>\n",
       "      <td>1</td>\n",
       "      <td>New</td>\n",
       "      <td>21203</td>\n",
       "      <td>Casey - South</td>\n",
       "      <td>212</td>\n",
       "      <td>Melbourne - South East</td>\n",
       "      <td>2GMEL</td>\n",
       "      <td>Greater Melbourne</td>\n",
       "      <td>2</td>\n",
       "      <td>Victoria</td>\n",
       "      <td>AUS</td>\n",
       "      <td>Australia</td>\n",
       "      <td>11.0254</td>\n",
       "      <td>http://linked.data.gov.au/dataset/asgsed3/SA2/...</td>\n",
       "      <td>POINT (145.31291 -38.10222)</td>\n",
       "      <td>12</td>\n",
       "      <td>47.402490</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>990</th>\n",
       "      <td>212021293</td>\n",
       "      <td>Berwick - North</td>\n",
       "      <td>0</td>\n",
       "      <td>No change</td>\n",
       "      <td>21202</td>\n",
       "      <td>Casey - North</td>\n",
       "      <td>212</td>\n",
       "      <td>Melbourne - South East</td>\n",
       "      <td>2GMEL</td>\n",
       "      <td>Greater Melbourne</td>\n",
       "      <td>2</td>\n",
       "      <td>Victoria</td>\n",
       "      <td>AUS</td>\n",
       "      <td>Australia</td>\n",
       "      <td>19.7480</td>\n",
       "      <td>http://linked.data.gov.au/dataset/asgsed3/SA2/...</td>\n",
       "      <td>POINT (145.34885 -38.02511)</td>\n",
       "      <td>32</td>\n",
       "      <td>47.426478</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1010</th>\n",
       "      <td>212031558</td>\n",
       "      <td>Cranbourne East - South</td>\n",
       "      <td>1</td>\n",
       "      <td>New</td>\n",
       "      <td>21203</td>\n",
       "      <td>Casey - South</td>\n",
       "      <td>212</td>\n",
       "      <td>Melbourne - South East</td>\n",
       "      <td>2GMEL</td>\n",
       "      <td>Greater Melbourne</td>\n",
       "      <td>2</td>\n",
       "      <td>Victoria</td>\n",
       "      <td>AUS</td>\n",
       "      <td>Australia</td>\n",
       "      <td>5.3272</td>\n",
       "      <td>http://linked.data.gov.au/dataset/asgsed3/SA2/...</td>\n",
       "      <td>POINT (145.30423 -38.12247)</td>\n",
       "      <td>13</td>\n",
       "      <td>47.691723</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>973</th>\n",
       "      <td>211051278</td>\n",
       "      <td>Lilydale - Coldstream</td>\n",
       "      <td>0</td>\n",
       "      <td>No change</td>\n",
       "      <td>21105</td>\n",
       "      <td>Yarra Ranges</td>\n",
       "      <td>211</td>\n",
       "      <td>Melbourne - Outer East</td>\n",
       "      <td>2GMEL</td>\n",
       "      <td>Greater Melbourne</td>\n",
       "      <td>2</td>\n",
       "      <td>Victoria</td>\n",
       "      <td>AUS</td>\n",
       "      <td>Australia</td>\n",
       "      <td>109.3817</td>\n",
       "      <td>http://linked.data.gov.au/dataset/asgsed3/SA2/...</td>\n",
       "      <td>POINT (145.38884 -37.71375)</td>\n",
       "      <td>9</td>\n",
       "      <td>48.377052</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>998</th>\n",
       "      <td>212021553</td>\n",
       "      <td>Berwick - South East</td>\n",
       "      <td>1</td>\n",
       "      <td>New</td>\n",
       "      <td>21202</td>\n",
       "      <td>Casey - North</td>\n",
       "      <td>212</td>\n",
       "      <td>Melbourne - South East</td>\n",
       "      <td>2GMEL</td>\n",
       "      <td>Greater Melbourne</td>\n",
       "      <td>2</td>\n",
       "      <td>Victoria</td>\n",
       "      <td>AUS</td>\n",
       "      <td>Australia</td>\n",
       "      <td>9.8836</td>\n",
       "      <td>http://linked.data.gov.au/dataset/asgsed3/SA2/...</td>\n",
       "      <td>POINT (145.35672 -38.06447)</td>\n",
       "      <td>19</td>\n",
       "      <td>49.800358</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>249 rows × 19 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     SA2_CODE21                    SA2_NAME21 CHG_FLAG21  CHG_LBL21  \\\n",
       "780   206041504         Melbourne CBD - North          1        New   \n",
       "781   206041505          Melbourne CBD - West          1        New   \n",
       "779   206041503          Melbourne CBD - East          1        New   \n",
       "771   206041117                       Carlton          0  No change   \n",
       "786   206041510  West Melbourne - Residential          1        New   \n",
       "...         ...                           ...        ...        ...   \n",
       "1009  212031557       Cranbourne East - North          1        New   \n",
       "990   212021293               Berwick - North          0  No change   \n",
       "1010  212031558       Cranbourne East - South          1        New   \n",
       "973   211051278         Lilydale - Coldstream          0  No change   \n",
       "998   212021553          Berwick - South East          1        New   \n",
       "\n",
       "     SA3_CODE21      SA3_NAME21 SA4_CODE21              SA4_NAME21 GCC_CODE21  \\\n",
       "780       20604  Melbourne City        206       Melbourne - Inner      2GMEL   \n",
       "781       20604  Melbourne City        206       Melbourne - Inner      2GMEL   \n",
       "779       20604  Melbourne City        206       Melbourne - Inner      2GMEL   \n",
       "771       20604  Melbourne City        206       Melbourne - Inner      2GMEL   \n",
       "786       20604  Melbourne City        206       Melbourne - Inner      2GMEL   \n",
       "...         ...             ...        ...                     ...        ...   \n",
       "1009      21203   Casey - South        212  Melbourne - South East      2GMEL   \n",
       "990       21202   Casey - North        212  Melbourne - South East      2GMEL   \n",
       "1010      21203   Casey - South        212  Melbourne - South East      2GMEL   \n",
       "973       21105    Yarra Ranges        211  Melbourne - Outer East      2GMEL   \n",
       "998       21202   Casey - North        212  Melbourne - South East      2GMEL   \n",
       "\n",
       "             GCC_NAME21 STE_CODE21 STE_NAME21 AUS_CODE21 AUS_NAME21  \\\n",
       "780   Greater Melbourne          2   Victoria        AUS  Australia   \n",
       "781   Greater Melbourne          2   Victoria        AUS  Australia   \n",
       "779   Greater Melbourne          2   Victoria        AUS  Australia   \n",
       "771   Greater Melbourne          2   Victoria        AUS  Australia   \n",
       "786   Greater Melbourne          2   Victoria        AUS  Australia   \n",
       "...                 ...        ...        ...        ...        ...   \n",
       "1009  Greater Melbourne          2   Victoria        AUS  Australia   \n",
       "990   Greater Melbourne          2   Victoria        AUS  Australia   \n",
       "1010  Greater Melbourne          2   Victoria        AUS  Australia   \n",
       "973   Greater Melbourne          2   Victoria        AUS  Australia   \n",
       "998   Greater Melbourne          2   Victoria        AUS  Australia   \n",
       "\n",
       "      AREASQKM21                                         LOCI_URI21  \\\n",
       "780       0.5616  http://linked.data.gov.au/dataset/asgsed3/SA2/...   \n",
       "781       1.0051  http://linked.data.gov.au/dataset/asgsed3/SA2/...   \n",
       "779       0.8020  http://linked.data.gov.au/dataset/asgsed3/SA2/...   \n",
       "771       1.8187  http://linked.data.gov.au/dataset/asgsed3/SA2/...   \n",
       "786       0.8247  http://linked.data.gov.au/dataset/asgsed3/SA2/...   \n",
       "...          ...                                                ...   \n",
       "1009     11.0254  http://linked.data.gov.au/dataset/asgsed3/SA2/...   \n",
       "990      19.7480  http://linked.data.gov.au/dataset/asgsed3/SA2/...   \n",
       "1010      5.3272  http://linked.data.gov.au/dataset/asgsed3/SA2/...   \n",
       "973     109.3817  http://linked.data.gov.au/dataset/asgsed3/SA2/...   \n",
       "998       9.8836  http://linked.data.gov.au/dataset/asgsed3/SA2/...   \n",
       "\n",
       "                         geometry  count   cbd_dist  \n",
       "780   POINT (144.96089 -37.80918)    252   0.000000  \n",
       "781   POINT (144.95871 -37.81672)    200   0.728392  \n",
       "779   POINT (144.96860 -37.81277)    138   0.917602  \n",
       "771   POINT (144.96781 -37.80049)    218   1.103787  \n",
       "786   POINT (144.94977 -37.80857)     67   1.237667  \n",
       "...                           ...    ...        ...  \n",
       "1009  POINT (145.31291 -38.10222)     12  47.402490  \n",
       "990   POINT (145.34885 -38.02511)     32  47.426478  \n",
       "1010  POINT (145.30423 -38.12247)     13  47.691723  \n",
       "973   POINT (145.38884 -37.71375)      9  48.377052  \n",
       "998   POINT (145.35672 -38.06447)     19  49.800358  \n",
       "\n",
       "[249 rows x 19 columns]"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X2 = X[['SA2_NAME21']].groupby(by=\"SA2_NAME21\")[\"SA2_NAME21\"].count()\n",
    "X2 = pd.DataFrame(X2)\n",
    "X2.columns=[\"count\"]\n",
    "X3 = vic_centroid_sf.join(X2, how='inner',on='SA2_NAME21')\n",
    "\n",
    "X3['cbd_dist'] = X3.apply (lambda row: point_to_dist(row), axis=1)\n",
    "X3.sort_values(by=['cbd_dist'], inplace=True)\n",
    "X3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "75aeb7b2",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>cbd_dist</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>SA2_NAME21</th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Melbourne CBD - North</th>\n",
       "      <td>0.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Melbourne CBD - West</th>\n",
       "      <td>0.728392</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Melbourne CBD - East</th>\n",
       "      <td>0.917602</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Carlton</th>\n",
       "      <td>1.103787</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>West Melbourne - Residential</th>\n",
       "      <td>1.237667</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Cranbourne East - North</th>\n",
       "      <td>47.402490</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Berwick - North</th>\n",
       "      <td>47.426478</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Cranbourne East - South</th>\n",
       "      <td>47.691723</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Lilydale - Coldstream</th>\n",
       "      <td>48.377052</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Berwick - South East</th>\n",
       "      <td>49.800358</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>249 rows × 1 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                               cbd_dist\n",
       "SA2_NAME21                             \n",
       "Melbourne CBD - North          0.000000\n",
       "Melbourne CBD - West           0.728392\n",
       "Melbourne CBD - East           0.917602\n",
       "Carlton                        1.103787\n",
       "West Melbourne - Residential   1.237667\n",
       "...                                 ...\n",
       "Cranbourne East - North       47.402490\n",
       "Berwick - North               47.426478\n",
       "Cranbourne East - South       47.691723\n",
       "Lilydale - Coldstream         48.377052\n",
       "Berwick - South East          49.800358\n",
       "\n",
       "[249 rows x 1 columns]"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "pruned_X3 = X3[['SA2_NAME21', \"cbd_dist\"]]\n",
    "pruned_X3.set_index('SA2_NAME21', inplace=True)\n",
    "pruned_X3\n",
    "#pruned_X3.join(X, how='left', on=\"SA2_NAME21\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "e6b502f2",
   "metadata": {},
   "outputs": [],
   "source": [
    "X_dists = X.join(pruned_X3, how='left', on=\"SA2_NAME21\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "f5e197c2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\tnum training instances:  10860\n"
     ]
    }
   ],
   "source": [
    "sl = 50\n",
    "scaler = StandardScaler()\n",
    "numeric_features = [ \n",
    "                  \"Median_tot_prsnl_inc_weekly\", \n",
    "                  \"Median_rent_weekly\",\n",
    "                  \"Median_tot_fam_inc_weekly\", \n",
    "                  \"Median_tot_hhd_inc_weekly\", \n",
    "                  \"total_population\",\n",
    "                  \"Bed\", \n",
    "                  \"Bath\", \n",
    "                  \"Park\",\n",
    "                  \"Offence Count\",\n",
    "                  \"cbd_dist\"]\n",
    "numeric_transformer = Pipeline(steps=[\n",
    "    ('scaler', StandardScaler())])\n",
    "\n",
    "preprocessor = ColumnTransformer(\n",
    "    transformers=[\n",
    "        ('num', scaler, numeric_features)])\n",
    "\n",
    "y = X_dists['cost_text'].tolist()\n",
    "print(\"\\tnum training instances: \", len(y))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "fcdea116",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(10860, 12)"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data = X_dists.drop([\"index\", \"address\", \"desc_head\", \"latitude\", \"longitude\", \"LocID\", \"SA2_CODE_2021\", \n",
    "              \"cost_text\", \"SA2_NAME21\"], axis=1)\n",
    "data.astype({ \n",
    "          \"Median_tot_prsnl_inc_weekly\":\"float\", \n",
    "          \"Median_rent_weekly\":\"float\",\n",
    "          \"Median_tot_fam_inc_weekly\":\"float\", \n",
    "          \"Median_tot_hhd_inc_weekly\":\"float\", \n",
    "          \"total_population\": \"int64\",\n",
    "          \"duration_mins\": \"category\", \n",
    "          \"Bed\":\"int32\", \n",
    "          \"Bath\":\"int32\", \n",
    "          \"Park\":\"int32\",\n",
    "          \"property_type\":\"category\",\n",
    "          #\"SA2_NAME21\": \"category\",\n",
    "          \"Offence Count\": \"int32\",\n",
    "          \"cbd_dist\": \"float\"}).dtypes\n",
    "data.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "6ea48044",
   "metadata": {},
   "outputs": [],
   "source": [
    "# define base model\n",
    "def baseline_model():\n",
    "    # create model\n",
    "    model = Sequential()\n",
    "    model.add(Dense(100, input_shape=(12,), kernel_initializer='normal', activation='relu'))\n",
    "    model.add(Dense(32, kernel_initializer='normal', activation='relu'))\n",
    "    model.add(Dense(1, kernel_initializer='normal', activation=\"sigmoid\"))\n",
    "    # Compile model\n",
    "    model.compile(loss='mean_squared_error', optimizer='adam')\n",
    "    return model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "0f1802bf",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-10-01 13:20:56.052124: E tensorflow/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: CUDA_ERROR_SYSTEM_DRIVER_MISMATCH: system has unsupported display driver / cuda driver combination\n",
      "2022-10-01 13:20:56.052168: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: uwu\n",
      "2022-10-01 13:20:56.052176: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: uwu\n",
      "2022-10-01 13:20:56.052288: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 515.65.1\n",
      "2022-10-01 13:20:56.052312: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 390.154.0\n",
      "2022-10-01 13:20:56.052318: E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:313] kernel version 390.154.0 does not match DSO version 515.65.1 -- cannot find working devices in this configuration\n",
      "2022-10-01 13:20:56.052616: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[nan nan nan nan nan nan nan nan nan nan]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/sesshah/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: \n",
      "10 fits failed out of a total of 10.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 762, in fit\n",
      "    self._fit(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 931, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 526, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"/tmp/__autograph_generated_file3bw40e6h.py\", line 15, in tf__train_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1160, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1146, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1135, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 993, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential\" is incompatible with the layer: expected shape=(None, 12), found shape=(None, 10)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 762, in fit\n",
      "    self._fit(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 931, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 526, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"/tmp/__autograph_generated_file3bw40e6h.py\", line 15, in tf__train_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1160, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1146, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1135, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 993, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_1\" is incompatible with the layer: expected shape=(None, 12), found shape=(None, 10)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 762, in fit\n",
      "    self._fit(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 931, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 526, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"/tmp/__autograph_generated_file3bw40e6h.py\", line 15, in tf__train_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1160, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1146, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1135, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 993, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_2\" is incompatible with the layer: expected shape=(None, 12), found shape=(None, 10)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 762, in fit\n",
      "    self._fit(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 931, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 526, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"/tmp/__autograph_generated_file3bw40e6h.py\", line 15, in tf__train_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1160, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1146, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1135, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 993, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_3\" is incompatible with the layer: expected shape=(None, 12), found shape=(None, 10)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 762, in fit\n",
      "    self._fit(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 931, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 526, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"/tmp/__autograph_generated_file3bw40e6h.py\", line 15, in tf__train_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1160, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1146, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1135, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 993, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_4\" is incompatible with the layer: expected shape=(None, 12), found shape=(None, 10)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 762, in fit\n",
      "    self._fit(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 931, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 526, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"/tmp/__autograph_generated_file3bw40e6h.py\", line 15, in tf__train_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1160, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1146, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1135, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 993, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_5\" is incompatible with the layer: expected shape=(None, 12), found shape=(None, 10)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 762, in fit\n",
      "    self._fit(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 931, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 526, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"/tmp/__autograph_generated_file3bw40e6h.py\", line 15, in tf__train_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1160, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1146, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1135, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 993, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_6\" is incompatible with the layer: expected shape=(None, 12), found shape=(None, 10)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 762, in fit\n",
      "    self._fit(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 931, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 526, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"/tmp/__autograph_generated_file3bw40e6h.py\", line 15, in tf__train_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1160, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1146, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1135, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 993, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_7\" is incompatible with the layer: expected shape=(None, 12), found shape=(None, 10)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 762, in fit\n",
      "    self._fit(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 931, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 526, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"/tmp/__autograph_generated_file3bw40e6h.py\", line 15, in tf__train_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1160, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1146, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1135, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 993, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_8\" is incompatible with the layer: expected shape=(None, 12), found shape=(None, 10)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 762, in fit\n",
      "    self._fit(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 931, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 526, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"/tmp/__autograph_generated_file3bw40e6h.py\", line 15, in tf__train_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1160, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1146, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1135, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 993, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_9\" is incompatible with the layer: expected shape=(None, 12), found shape=(None, 10)\n",
      "\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n"
     ]
    }
   ],
   "source": [
    "estimator = KerasRegressor(model=baseline_model, epochs=200, verbose=0)\n",
    "kfold = KFold(n_splits=10, shuffle=True, random_state=30027)\n",
    "\n",
    "results = cross_val_score(estimator, preprocessor.fit_transform(data), y, cv=kfold)\n",
    "print(results)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "569dce14",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
